POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick
TRI_LAYER_ENABLE = yes
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
BACKLIGHT_ENABLE = no
COMBO_ENABLE = yes
KEYBOARD_SHARED_EP = yes
